services: 
  postgres: 
    image: postgres:latest
    container_name: landlord_pg
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: zeRdojD7
      POSTGRES_DB: landlord_dev
    ports:
    - '5432:5432'
    volumes:
    - landlord_pg_vol:/var/lib/postgresql/data
    restart: always

volumes:
  landlord_pg_vol: